export const GET_TOP_ARTICLES = 'GET_TOP_ARTICLES';
export const FETCHING_TOP_ARTICLES = 'FETCHING_TOP_ARTICLES';
export const GOT_TOP_ARTICLES = 'GOT_TOP_ARTICLES';
export const FETCHING_TOP_ARTICLES_ERROR = 'FETCHING_TOP_ARTICLES_ERROR';

export const GET_ARTICLES_BY_CATEGORY = 'GET_ARTICLES_BY_CATEGORY';
export const FETCHING_ARTICLES_BY_CATEGORY = 'FETCHING_ARTICLES_BY_CATEGORY';
export const GOT_ARTICLES_BY_CATEGORY = 'GOT_ARTICLES_BY_CATEGORY';
export const FETCHING_ARTICLES_BY_CATEGORY_ERROR = 'FETCHING_ARTICLES_BY_CATEGORY_ERROR';

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const CHANGED_CATEGORY = 'CHANGED_CATEGORY';